### ISSUE TITLE
可以支持翻译 issue 标题吗？

### ISSUE THREAD

**Issue by sangshuduo** [dromara/issues-translate-action#42]
可以支持翻译 issue 标题吗？

**Comment by tomsun28** [comment]
你好可以支持的，你看楼上

**Comment by sangshuduo** [comment]
呃，我其实是希望可以直接修改 issue 的标题，而不是在新的 comment 中的 Title: ...

**Comment by tomsun28** [comment]
这个可以在下个版本做个开关支持下，不过需要给机器人账户修改权限

**Comment by sangshuduo** [comment]
非常期待

**Comment by tomsun28** [comment]
@sangshuduo 新版本已支持 欢迎使用  这个需要将@Issues-translate-bot加入到仓库协作者这样才有权限修改issue  建议配置使用自己的机器人账户，更安全

**Comment by sangshuduo** [comment]
已经邀请，看状态是 pending，所以是需要您那边手工接受才行？

**Comment by tomsun28** [comment]
是的，刚刚已经接受，您试试呢

**Comment by sangshuduo** [comment]
我按照官方实例加了

```
with:
          IS_MODIFY_TITLE: false
```

然后加入的中文 issue 没有翻译，是哪里写错了吗？原始 yaml 文件在：

https://github.com/sangshuduo/postress/blob/main/.github/workflows/issue-translator.yml

**Comment by tomsun28** [comment]
````
        with:
          IS_MODIFY_TITLE: true
````
IS_MODIFY_TITLE 在with下方后两个space对齐试试呢

**Comment by sangshuduo** [comment]
改了也没有变化，BTW，这里的 comments 对话也没有翻译

**Comment by tomsun28** [comment]
github action yml格式比较严格 还是格式有点小问题，已经提了个pr您看下 https://github.com/sangshuduo/postress/pull/10 ，上面两个comment未翻译是因为计算出它的第一占有率语言是英文了(里面有代码被算成了英文)，我之后优化下

**Comment by sangshuduo** [comment]
繁体中文可以支持吗？

**Comment by tomsun28** [comment]
可以的，支持常见的非英文，法语日语中文俄语等。 

你好我來自台灣，很高興能使用這個項目。這裡有一個小問題。

**Comment by sangshuduo** [comment]
非常感谢，非常棒的 project

**Comment by moegirlwangge** [comment]
@tomsun28 
目前的情况是：
```
**Title:** [标题内容]
```
我建议标题翻译可以修改成这个样子：
```
## [标题内容]
```

**Comment by tomsun28** [comment]
@nc-animation 好的 这个在下一个版本修改好
