### ISSUE TITLE
Title translation

### ISSUE THREAD

**Issue by Nayacco** [dromara/issues-translate-action#55]
如果开启了标题翻译，不管 issue 的内容是否达到翻译的指标，**标题**检测到非英文时，是否都应该翻译呢？

![image](https://user-images.githubusercontent.com/22909744/129476338-8b794b25-9f7a-4947-9a99-196fc9d41f54.png)

![image](https://user-images.githubusercontent.com/22909744/129476351-44d52408-0d34-4d2c-9371-5bbb2e254d00.png)

**Comment by tomsun28** [comment]
hi, 目前判断是否英文，是根据所有内容的语言占比最大的那个语言来判断的，因为截图中的内容占比最大的是英文，所以造成了这个bug 此问题具体ISSUE见 https://github.com/usthe/issues-translate-action/issues/48 。之后考虑修改判断是否英文的方式，如果你有啥好的方式，欢迎PR

**Comment by Nayacco** [comment]
可能我没有表达清楚，我说的是标题的问题，按理说 issue 内容和 issue 标题是两个部分（两个不同的 update api ）。标题应该单独做检测翻译的

**Comment by tomsun28** [comment]
好的 这两天改一下

**Comment by tomsun28** [comment]
@GoldSubmarine Hi, 问题已在2.6版本修改，但由于还没找到较好的语言判断方式，当英文占比最大时会忽略翻译这个问题暂未解决。

**Comment by Nayacco** [comment]
Good job! 🎉
